CREATE TABLE Autor (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(100) NOT NULL,
    nacionalidade VARCHAR(50)
);

CREATE TABLE Livro (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    titulo VARCHAR(255) NOT NULL,
    ano_publicacao INTEGER,
    id_autor INTEGER NOT NULL,
    FOREIGN KEY (id_autor) REFERENCES Autor(id) ON DELETE CASCADE
);
